[package]
name = "render_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = { workspace = true }
bytemuck = { workspace = true }
futures = { workspace = true }
anyhow = { workspace = true }
image = { workspace = true }

tracing = "0.1"
rust-embed = "8"
